#!/usr/bin/env php
<?php

use Bench\RunnerCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Finder\Finder;

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require_once $file;
    }
}

$application = new Application();
$application->add(new RunnerCommand(new Finder()));
$application->run();

