#!/usr/bin/env php
<?php

use Bench\RunnerCommand;
use Symfony\Component\Console\Application;

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->add(new RunnerCommand());
$application->run();

