#!/usr/bin/env php
<?php

use Bench\RunnerCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Finder\Finder;

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->add(new RunnerCommand(new Finder()));
$application->run();

